[package]
name = "aftr"
version = "0.1.0"
description = "An open-source implementation of BYOND's Dream Maker programming language."
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
